services:
  mysql:
    image: crpi-w1x1q83txaky0cp1.cn-hangzhou.personal.cr.aliyuncs.com/howtotalk/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "howtotalk"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Shanghai"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_0900_ai_ci"
    volumes:
      # 数据持久化
      - /home/howtotalk/mysql/data:/var/lib/mysql
      # 自定义配置文件
      - /home/howtotalk/mysql/conf:/etc/mysql/conf.d
      # 初始化脚本目录
      - /home/howtotalk/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: crpi-w1x1q83txaky0cp1.cn-hangzhou.personal.cr.aliyuncs.com/howtotalk/redis:7.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /home/howtotalk/redis:/data
    restart: unless-stopped

  backend:
    image: crpi-w1x1q83txaky0cp1.cn-hangzhou.personal.cr.aliyuncs.com/howtotalk/backend:latest
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped

  web:
    image: crpi-w1x1q83txaky0cp1.cn-hangzhou.personal.cr.aliyuncs.com/howtotalk/web:latest
    depends_on:
      - backend
    environment:
      WEB_ENV: prod
      BACKEND_PORT: 443
      API_BASE_URL: https://api.huangruoyi.cn
    # 由 gateway 统一对外暴露 80/443，这里仅在 Docker 内网提供服务
    restart: unless-stopped

  gateway:
    image: crpi-w1x1q83txaky0cp1.cn-hangzhou.personal.cr.aliyuncs.com/howtotalk/nginx:1.27-alpine
    depends_on:
      - web
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /ssl:/etc/nginx/ssl:ro
      # 可在宿主机该目录放置微信校验文件 MP_verify_*.txt
      - /home/howtotalk/html:/usr/share/nginx/html:rw
      # 需要新增/调整规则时，直接修改该文件并重启 gateway
      - /home/howtotalk/gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes: {}
